FROM node:alpine
WORKDIR /app/user

COPY adminMongo/package.json .
RUN npm install --production

COPY adminMongo/ .
COPY adminMongo_config.json ./config/config.json
COPY adminMongo_entrypoint.sh entrypoint.sh

EXPOSE 1234
CMD ["sh", "entrypoint.sh"]
